CREATE OR REPLACE TRIGGER "DS2"."GENERATECUSTOMERID" 
BEFORE INSERT ON "DS2"."CUSTOMERS" 
FOR EACH ROW 
BEGIN
  SELECT "DS2"."CUSTOMERID_SEQ".nextval into :new.CUSTOMERID from dual;
END GENERATECUSTOMERID;
/

CREATE OR REPLACE TRIGGER "DS2"."GENERATEORDERID" 
BEFORE INSERT ON "DS2"."ORDERS" 
FOR EACH ROW 
BEGIN
  SELECT "DS2"."ORDERID_SEQ".nextval into :new.ORDERID from dual;
END GENERATEORDERID;
/

exit;